import {useEffect,useState} from "react";
import {Link,useNavigate,useParams} from "react-router-dom";
import {deletePost,favoritePost,getComments,getPost,likePost,unfavoritePost,unlikePost,type CommunityComment,type CommunityPost} from "../api/community";
import {getAssetUrl} from "../api/client";
import CommentSection from "../components/community/CommentSection";

export default function CommunityPostDetail(){
  const {id}=useParams();const nav=useNavigate();const [post,setPost]=useState<CommunityPost>();const [comments,setComments]=useState<CommunityComment[]>([]);const [error,setError]=useState('');
  useEffect(()=>{if(!id)return;Promise.all([getPost(Number(id)),getComments(Number(id))]).then(([p,c])=>{setPost(p);setComments(c)}).catch(e=>setError(e.message))},[id]);
  if(error&&!post)return <main className="handwriting-page container-page"><div className="card">{error}</div></main>;
  if(!post)return <main className="handwriting-page container-page"><div className="inspiration-skeleton"/></main>;
  async function toggleLike(){const r=await(post!.is_liked?unlikePost(post!.id):likePost(post!.id));setPost({...post!,is_liked:r.liked,like_count:r.like_count})}
  async function toggleFavorite(){const r=await(post!.is_favorited?unfavoritePost(post!.id):favoritePost(post!.id));setPost({...post!,is_favorited:r.favorited,favorite_count:r.favorite_count})}
  const metadata=[['设备',post.device_name],['镜头',post.lens_name],['光圈',post.aperture],['快门',post.shutter_speed],['ISO',post.iso],['焦距',post.focal_length]].filter(x=>x[1]);
  return <main className="handwriting-page container-page"><article className="grid gap-8 lg:grid-cols-[1.25fr_.75fr]"><section><div className="space-y-4">{post.images.map((im,i)=><img key={im.id||i} className="h-auto w-full rounded-3xl bg-neutral-100" src={getAssetUrl(im.image_url)} alt={im.alt_text||post.title}/>)}</div></section><aside><div className="sticky top-28"><div className="flex items-center justify-between"><Link to={`/users/${post.author.id}`} className="flex items-center gap-3">{post.author.avatar_url?<img className="h-11 w-11 rounded-full object-cover" src={getAssetUrl(post.author.avatar_url)} alt=""/>:<span className="flex h-11 w-11 items-center justify-center rounded-full bg-blush">{post.author.username[0]}</span>}<div><strong>{post.author.username}</strong><p className="text-xs text-muted">{post.author.signature}</p></div></Link>{post.is_owner&&<div className="flex gap-2"><Link className="btn-ghost" to={`/community/post/${post.id}/edit`}>编辑</Link><button className="btn-ghost" onClick={async()=>{if(confirm('确定删除这篇帖子吗？')){await deletePost(post.id);nav('/community')}}}>删除</button></div>}</div><h1 className="mt-8 font-display text-4xl font-semibold">{post.title}</h1><p className="mt-5 whitespace-pre-wrap leading-8">{post.content}</p><div className="mt-5 flex flex-wrap gap-2">{post.tags.map(t=><span className="rounded-full bg-blush px-3 py-1 text-sm text-brand-deep" key={t.slug}>#{t.name}</span>)}</div>{metadata.length>0&&<dl className="mt-6 grid grid-cols-2 gap-3 rounded-2xl bg-white/60 p-4 text-sm">{metadata.map(x=><div key={String(x[0])}><dt className="text-xs text-muted">{x[0]}</dt><dd>{x[1]}</dd></div>)}</dl>}<div className="mt-7 flex gap-3 border-y border-sand py-4"><button className={post.is_liked?'btn-primary':'btn-secondary'} onClick={toggleLike}>喜欢 {post.like_count}</button><button className={post.is_favorited?'btn-primary':'btn-secondary'} onClick={toggleFavorite}>收藏 {post.favorite_count}</button><button className="btn-secondary" onClick={()=>navigator.share?navigator.share({title:post.title,url:location.href}):navigator.clipboard.writeText(location.href)}>分享</button></div><CommentSection postId={post.id} allowComments={post.allow_comments} comments={comments} setComments={setComments} onCreated={()=>setPost(current=>current?{...current,comment_count:current.comment_count+1}:current)}/></div></aside></article></main>
}
